#pragma once

#define PORT 8080
#define MAX_CLIENTS 2
#define INPUT_BUFFER_SIZE 256

#define INITIAL_SCORE 0
#define INITIAL_LIVES 3
#define INITIAL_LEVEL 1
#define INITIAL_BALL_QUANTITY 0

#define MAX_BALLS 10
#define INITIAL_POS_X 200;
#define INITIAL_POS_Y 200;

#define BLOCK_ROWS 8
#define BLOCK_COLUMNS 8
#define BASE_POINTS 100

#define INITIAL_PADDLE_WIDTH 45
#define INITIAL_PADDLE_POSITION 200
#define INITIAL_PADDLE_SPEED 5